version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    container_name: t24_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-t24_leads}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Backend API
  backend:
    build: ./backend
    container_name: t24_backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-t24_leads}
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - LEAD_EXPIRY_HOURS=${LEAD_EXPIRY_HOURS:-48}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@t24leads.se}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # Frontend
  frontend:
    build: ./frontend
    container_name: t24_frontend
    depends_on:
      - backend
    ports:
      - "80:80"    # hostPort:containerPort remapped for easy access
    restart: unless-stopped

volumes:
  postgres_data: {}
